version: '3.8'

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    networks:
      - backend
    environment:
      MYSQL_DATABASE: "symfony"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root"]
      timeout: 5s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql

  php:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    links:
      - db
    networks:
      - backend
    env_file:
      - ./symfony/.env
    volumes:
      - ./logs/php-fpm/:/var/log/php
      - ./symfony:/app
    ports:
      - 80:80
      - 443:443

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
